# Generated by Django 5.0.3 on 2024-03-24 14:13

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('initiative', models.IntegerField(default=0)),
                ('armour_class', models.IntegerField()),
                ('hit_points', models.IntegerField()),
                ('status', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('bl', 'Blinded'), ('ch', 'Charmed'), ('df', 'Deafened'), ('fr', 'Frightened'), ('inc', 'Incapacitated'), ('inv', 'Invisible'), ('par', 'Paralyzed'), ('pet', 'Petrified'), ('pois', 'Poisoned'), ('pr', 'Prone'), ('rt', 'Restrained'), ('st', 'Stunned'), ('unc', 'Unconscious')]), size=None)),
                ('description', models.TextField(max_length=500)),
                ('encounters', models.ManyToManyField(to='inittracker.encounter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('initiative', models.IntegerField(default=0)),
                ('armour_class', models.IntegerField()),
                ('status', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('bl', 'Blinded'), ('ch', 'Charmed'), ('df', 'Deafened'), ('fr', 'Frightened'), ('inc', 'Incapacitated'), ('inv', 'Invisible'), ('par', 'Paralyzed'), ('pet', 'Petrified'), ('pois', 'Poisoned'), ('pr', 'Prone'), ('rt', 'Restrained'), ('st', 'Stunned'), ('unc', 'Unconscious')]), size=None)),
                ('description', models.TextField(max_length=500)),
                ('encounters', models.ManyToManyField(to='inittracker.encounter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
