# Generated by Django 5.0.3 on 2024-03-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inittracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='player',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
